version: "3.9"

services:
    app:
        build:
            dockerfile: Dockerfile
            context: .
        ports:
          - "5000:5000"
        volumes:
            - ./:/app
        environment:
            - DATABASE_URL=db
        depends_on:
            - db
    db:
        image: postgres:alpine
        ports:
            - "5432:5432"
        volumes:
            - ./initdb.d:/docker-entrypoint-initdb.d/
            - database-data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: gotest
            POSTGRES_USER: gouser
            POSTGRES_PASSWORD: gopassword

volumes:
  database-data:
